version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: snmsung1
      MYSQL_DATABASE: writedream
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: snmsung1
      DB_NAME: writedream
