version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: snmsung1
      MYSQL_DATABASE: writedream
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: snmsung1
      DB_NAME: writedream
